### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Cleanspeech317** [Ti1bur/2022WeChatBigDataChallenge#1]
请问可以分享一下数据集吗？denonisrs007@gmail.com

**Comment by Ti1bur** [comment]
> 请问可以分享一下数据集吗？[denonisrs007@gmail.com](mailto:denonisrs007@gmail.com)

大赛官方的闭源平台操作的数据集， 赛方已销毁

**Comment by Cleanspeech317** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
                 请问初赛数据集也没有吗？
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                renyaqi233
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2022年8月19日 ***@***.***> 写道： 






***@***.***



大赛官方的闭源平台操作的数据集， 赛方已销毁



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Cleanspeech317** [comment]
> > 请问可以分享一下数据集吗？[denonisrs007@gmail.com](mailto:denonisrs007@gmail.com)
> 
> 大赛官方的闭源平台操作的数据集， 赛方已销毁
请问初赛数据集也没有吗？

**Comment by Ti1bur** [comment]
> 



> > > 请问可以分享一下数据集吗？[denonisrs007@gmail.com](mailto:denonisrs007@gmail.com)
> > 
> > 
> > 大赛官方的闭源平台操作的数据集， 赛方已销毁
> > 请问初赛数据集也没有吗？

赛方限制数据开源 属于业务数据
